### PR TITLE
Fix for issue #5 (in rails 3, 'rake db:schema:dump' does not dump the view)

### PR DESCRIPTION
**Pull request by rgabo**
Correctly makes MysqlAdapter.supports_views? public if it is defined by the original AR module (as in Rails 3.0.0)

### CODE REVIEW

**Comment by jsuchal** [comment]
Works like charm, thanks.

**Comment by flavorjones** [comment]
+1 this resolves the issue for me. Please apply!

**Comment by laripk** [comment]
This doesn't work with Rails 3.0.7 & mysql2 (I tried copying the changes over). I found that supports_views? is public while inside included(), but when the crucial call comes about in SchemaDumper#dump_with_views, supports_views? is private.

I kluged a work-around by adding 
    `@connection.class.send(:public, :supports_views?)`
right before the 
    `if @connection.supports_views?`
in schema_dumper.rb, but I know it's not a real fix.

**Comment by rgabo** [comment]
Most likely not compatible with recent Rails 3.x releases, closing.

**Pull request closed without merging**
